---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: scylla-demo
  region: eu-central-1

nodeGroups:
  - name: operator-pool
    instanceType: t3.small
    desiredCapacity: 1
    tags:
      keep: "48"
