---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: scylla-nop
  region: eu-central-1

nodeGroups:
  - name: scylla-pool
    instanceType: i3.2xlarge
    desiredCapacity: 1
    tags:
      keep: "48"
    labels:
      pool: "scylla-pool"
    taints:
      role: "scylla-clusters:NoSchedule"
    ssh:
      allow: true
    preBootstrapCommands:
      - curl -o /etc/yum.repos.d/scylla.repo -L http://repositories.scylladb.com/scylla/repo/e6090d0f-1820-4ff7-b354-32d71e30f761/centos/scylladb-4.0.repo
      - yum install -y scylla-server
      - yum install -y hwloc ethtool psmisc syssta
      - scylla_raid_setup --disks /dev/nvme0n1 --update-fstab
      - scylla_io_setup --ami
      - /opt/scylladb/scripts/perftune.py --nic eth0 --mode sq_split --tune net
      - scylla_cpuset_setup --cpuset 1-3,5-7
      - scylla_dev_mode_setup --developer-mode 0
      - echo "SCYLLA_DOCKER_ARGS=\"--listen-address $(hostname -i) --rpc-address $(hostname -i) --seed-provider-parameters seeds=$(hostname -i) --blocked-reactor-notify-ms 999999999\"" > /etc/scylla.d/docker.conf
    kubeletExtraConfig:
      cpuManagerPolicy: static

  - name: cassandra-stress-pool
    instanceType: c4.2xlarge
    desiredCapacity: 2
    tags:
      keep: "48"
    labels:
      pool: "cassandra-stress-pool"
    taints:
      role: "cassandra-stress:NoSchedule"
    ssh:
      allow: true
    preBootstrapCommands:
      - curl -o /etc/yum.repos.d/scylla.repo -L http://repositories.scylladb.com/scylla/repo/e6090d0f-1820-4ff7-b354-32d71e30f761/centos/scylladb-4.0.repo
      - yum install -y scylla-tools
