---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: scylla-demo10
  region: eu-central-1

nodeGroups:
  - name: scylla-pool-1
    instanceType: i3.2xlarge
    desiredCapacity: 1
    tags:
      keep: "48"
    labels:
      pool: "scylla-pool"
    taints:
      role: "scylla-clusters:NoSchedule"
    ssh:
      allow: true
    preBootstrapCommands:
      - cpupower frequency-set -g performance
      - curl -o /etc/yum.repos.d/scylla.repo -L http://repositories.scylladb.com/scylla/repo/e6090d0f-1820-4ff7-b354-32d71e30f761/centos/scylladb-4.0.repo
      - yum install -y scylla-server hwloc ethtool
      - /opt/scylladb/scripts/scylla_setup --ntp-domain amazon --no-coredump-setup --no-sysconfig-setup --no-raid-setup --no-io-setup --no-bootparam-setup --no-ec2-check --no-cpuscaling-setup
      - /opt/scylladb/scripts/scylla_raid_setup --disks /dev/nvme0n1 --root /mnt/raid-disks/disk0 --update-fstab
      - /opt/scylladb/scripts/perftune.py --nic eth0 --mode sq --tune net
    kubeletExtraConfig:
      cpuManagerPolicy: static

  - name: cassandra-stress-pool
    instanceType: c4.2xlarge
    desiredCapacity: 2
    tags:
      keep: "48"
    labels:
      pool: "cassandra-stress-pool"
    taints:
      role: "cassandra-stress:NoSchedule"
    ssh:
      allow: true
    preBootstrapCommands:
      - curl -o /etc/yum.repos.d/scylla.repo -L http://repositories.scylladb.com/scylla/repo/e6090d0f-1820-4ff7-b354-32d71e30f761/centos/scylladb-4.0.repo
      - yum install -y scylla-tools
